# Numpy Tutorial with all main functions

In [1]:
import numpy as np  # inmporting numpy 

In [20]:
# creating basic arrays

a = np.array([10,20,40,90,60,55])
b = np.array([50,60,70,25,55,67])

print(a)
print(b)
print(a+b) # array addition add the values of the array.
print(type(a))

[10 20 40 90 60 55]
[50 60 70 25 55 67]
[ 60  80 110 115 115 122]
<class 'numpy.ndarray'>


In [21]:
# slicing in arrays

print(a[0:2])
print(b[:3])



[10 20]
[50 60 70]


In [31]:
# inspecting an array
print(a.shape)
print(a.size)
print(len(a))
print(a.dtype)  
print(a.astype(str))  # converting type of array
x = np.sort(a)  # sorting array
print(x)


(6,)
6
6
int32
['10' '20' '40' '90' '60' '55']
[10 20 40 55 60 90]


In [35]:
# functions in array
c= a-b        # subtraction  
print(c)
c = a*b       # multiplication
print(c)
print(np.power(a,b))

[-40 -40 -30  65   5 -12]
[ 500 1200 2800 2250 3300 3685]
[        0         0         0 436207616         0 670019559]


In [38]:
# combining and spliting array

print(np.concatenate([a,b]))  # join two arrays  you can use hstack , vstack

print(np.array_split(a,3))   # splitting the array in 2 parts

[10 20 40 90 60 55 50 60 70 25 55 67]
[array([10, 20]), array([40, 90]), array([60, 55])]


In [51]:
# adding and removing array 

print(np.append(a,80))  # append add element at last
print(np.insert(b,1,40))  # insert add element at an index
print(np.delete(a,1))    # deletes the no at a specified index 
print(np.delete(b,1))

[10 20 40 90 60 55 80]
[50 40 60 70 25 55 67]
[10 40 90 60 55]
[50 70 25 55 67]


In [58]:
# sort filter and search

print(np.sort(a))   # sort the array

s= np.where(a == 55)  # search the array 
print(s)
print(a)



s = np.array([10, 20, 30, 40, 50, 60])                     # filter the arrays    
fa = np.array([True, False, True, False, True, False])
new = s[fa]
print(new)


[10 20 40 55 60 90]
(array([5], dtype=int64),)
[10 20 40 90 60 55]
[10 30 50]


In [63]:
# aggregating functions in numpy

print(np.sum(a))   # find the sum
print(np.max(a))   # find the max no
print(np.min(a))   # find the min no
print(np.mean(a))  # find the mean
print(np.cumsum(a)) # find the cumulative sum

275
90
10
45.833333333333336
[ 10  30  70 160 220 275]


In [79]:
# statistical function on array
import statistics as stat     # used for statistical functions


baked_food = [200,200,250,220,245,280,230]
z = np.array([baked_food])
print(z)
print(np.mean(baked_food))   # mean of all values
print(np.median(baked_food)) # median of all values
print(stat.mode(baked_food)) # finding mode using statistics library
print(np.std(baked_food))    #standard deviation 
print(np.var(baked_food))    # varience

print(np.corrcoef(a,b))      # corelation between 2 arrays (range from -1 to 1)


[[200 200 250 220 245 280 230]]
232.14285714285714
230.0
200
26.70702727977131
713.265306122449
[[ 1.         -0.53113304]
 [-0.53113304  1.        ]]


# End